### ISSUE TITLE
Account is probably ingame! Logged out!

### ISSUE THREAD

**Issue by Marcofurio30** [despa1r1337/reportbot#1]
Hello, i get this for every account : Account is probably ingame! Logged out!
Error: Disconnected

I've tried with around 45 accounts, they all have csgo

**Comment by verdammnis** [comment]
> Hello, i get this for every account : Account is probably ingame! Logged out!
> Error: Disconnected
> 
> I've tried with around 45 accounts, they all have csgo

Hello, I apologize for the late reply, your account has already been used in the reporter system, wait 12 hours, or create new accounts (you need 11 reports for the cheater to get ow ) If the error persists, please let me know.
