### ISSUE TITLE
Stuck at starting accounts

### ISSUE THREAD

**Issue by xMidNightFTW** [despa1r1337/reportbot#10]
I've followed every step and made sure everything is correct but everytime it stucks at this part

![rrrrr](https://user-images.githubusercontent.com/41029448/68524630-c123f100-02d1-11ea-80e3-06e602165fcc.PNG)

**Comment by verdammnis** [comment]
you have added your accounts to " account.txt"?

**Comment by xMidNightFTW** [comment]
Yes sir 
![gfjfgh](https://user-images.githubusercontent.com/41029448/68525344-2c24f600-02d9-11ea-9322-0bfd8b3317da.PNG)
heres some of the accounts

**Comment by verdammnis** [comment]
either your accounts have already been used in the reporting system, or your accounts do not have the game "counter - strike global offensive" in the library

**Comment by xMidNightFTW** [comment]
Yeah but in the tutorial u said it can have any game 

and i just made them never used them

i will try with counter strike selected then i will tell you

**Comment by verdammnis** [comment]
what steam account Registrar do you use?

**Comment by xMidNightFTW** [comment]
https://accgen.cathook.club/

**Comment by verdammnis** [comment]
![image](https://user-images.githubusercontent.com/48297813/68525519-7612d980-02e3-11ea-991a-23fc02398bd5.png)
sub id of the game Counter-Strike: Global Offensive: 303386, add this number to "Preference"

**Comment by xMidNightFTW** [comment]
alright im gonna try then let you know in probably 30 mins

**Comment by verdammnis** [comment]
okey

**Comment by xMidNightFTW** [comment]
Thx it worked, Can you state in the tutorial that it's mandatory to make counterstrike selected or in library? 

also thank you for the fast responses.

**Comment by xMidNightFTW** [comment]
13 Reports for this faggot.
Thanks for using Report Bot by despa1r!
