### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by addee99** [despa1r1337/reportbot#11]
Hey! I have like 1700 accounts i put in the "account.txt". Is is possible to choose how many reports I can send? Cause when I reported someone it did 280 reports.

**Comment by verdammnis** [comment]
> Hey! I have like 1700 accounts i put in the "account.txt". Is is possible to choose how many reports I can send? 

Hi, this is not in the script, but you can do it yourself.

**Comment by verdammnis** [comment]
>  Cause when I reported someone it did 280 reports.

1) your accounts have already been used in the reporting system

2) your accounts do not have Counter-Strike: Global Offensive in the library

**Comment by verdammnis** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
