### ISSUE TITLE
Stucking at last account/report.

### ISSUE THREAD

**Issue by justvetrex** [despa1r1337/reportbot#12]
When I send my reports (202 accounts), 69 accounts did not work (all account details are correct and csgo is registered in all the accounts), 133 accounts seem to work but it has been stuck in this screen for 3 hours. Are there ideas on how to fix the problem? 

Attached two screenshots: 

![screenshot 1](https://user-images.githubusercontent.com/58228216/69656849-924f9e00-1079-11ea-8ef9-1b0383d5a3a9.png)
![screenshot 2](https://user-images.githubusercontent.com/58228216/69656854-94b1f800-1079-11ea-9745-8f5b558cb930.png)

**Comment by verdammnis** [comment]
> When I send my reports (202 accounts), 69 accounts did not work (all account details are correct and csgo is registered in all the accounts), 

Hmm, maybe your accounts have a steam guard? email / 2fa? If this is the case, disable protection, as the bot only works with accounts that do not have steam guard protection.

**Comment by verdammnis** [comment]
>  133 accounts seem to work but it has been stuck in this screen for 3 hours. Are there ideas on how to fix the problem?

If your accounts are stuck on something, then this means:

your accounts have already been used in the reporting system, you must wait 12 hours, or create new accounts in which the game "Counter-Strike: Global Offensive" in the library

**Comment by justvetrex** [comment]
The accounts were not used in the last 12 hours.  The problem was that although they had CSGO registered but not with the sub id 303386. Newly created accounts with the subid work, thanks!

**Comment by verdammnis** [comment]
if your issue is resolved, you can close it.
