### ISSUE TITLE
Is report bot real?

### ISSUE THREAD

**Issue by ypc123** [despa1r1337/reportbot#13]
if the player is cheated, is the player banned? I will use if it helps to ban players with cheating

**Comment by despa1r1337** [comment]
this is a real reportbut, which sends the report with your accounts, after that, the suspect will be taken to the check (overwatch), and if he uses cheats he will be banned.

**Comment by ypc123** [comment]
The lack of match id is bad, great if the software works without match id.

**Comment by despa1r1337** [comment]
> The lack of match id is bad, great if the software works without match id.

if you want to do match ID support, then do it yourself.

**Comment by ypc123** [comment]
I don't encode it, you need to do it!

**Comment by despa1r1337** [comment]
> I don't encode it, you need to do it!

I don't plan on adding that

**Comment by Jaeger33211Sec** [comment]
matchid are 2 lines......
var matchId= readlineSync.question("Enter the Matchid of the match");

then exclude matchid: 8;
and insert matchid: matchId;

**Comment by ypc123** [comment]
@Jaeger33211Sec Where do I add this?

**Comment by Jaeger33211Sec** [comment]
Just write me discord.
Jaeger33211#5260
