### ISSUE TITLE
Yo Bro

### ISSUE THREAD

**Issue by ghost** [despa1r1337/reportbot#14]
How bout leaving at least credits to askwrite
You have 95% of his script copied and not giving any Credits

**Comment by verdammnis** [comment]
> How bout leaving at least credits to askwrite
> You have 95% of his script copied and not giving any Credits

Firstly: 
the script does not work with askwrite.

Secondly: 
what did i copy? 

Thirdly:
https://github.com/despa1r1337/reportbot/blob/f59fed21c1b18645db88c0f2b5b8191a097711f8/bot.js#L180

**Comment by ghost** [comment]
1. The script basically is askwrite...
2. Everything.
3. Its nice but what did you change about askwrites bot?

**Comment by ghost** [comment]
https://www.qualidator.com/WQM/Tools/TextDiff.aspx?c1=195
Here i inspected both codes.
1 = 1 the same with a "few" minor changes
and why did you not add the matchid options? Its added within 30 seconds and is basically easy if you know what your doing

**Comment by verdammnis** [comment]
> 1. The script basically is askwrite...
> 2. Everything.
> 3. Its nice but what did you change about askwrites bot?

1. He stopped supporting this project. I support it, because I think the report bot works. Even if it is founded, so what? Zonerbot is also based on this code, so what?

2. But what about the `GCProtoBufMsgSrc Unspecified message` error?
If everything is copied, why is it not there?

3. made it work and fixed error `GCProtoBufMsgSrc Unspecified message`

**Comment by verdammnis** [comment]
> https://www.qualidator.com/WQM/Tools/TextDiff.aspx?c1=195
> Here i inspected both codes.
> 1 = 1 the same with a "few" minor changes
> and why did you not add the matchid options? Its added within 30 seconds and is basically easy if you know what your doing

I will add it when I see fit. It has long been added to the beta version, which is with me.

**Comment by ghost** [comment]
My reportwebsite uses beep felixs script with serverid and matchid also i recoded it to mysql support.
So the unspecified is ez to fix

**Comment by verdammnis** [comment]
> My reportwebsite uses beep felixs script with serverid and matchid also i recoded it to mysql support.
> And Project unknown uses my report api.
> So the unspecified is ez to fix

and why do I need this information? Why did you create this issue? You have no problem? Close issue?

**Comment by ghost** [comment]
just wanted to remind you that you should give credits which you did. 
I didnt see it so iam sorry for opening this issue.
If you need help with the matchid let me know.
