### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by HuskyDotExe** [despa1r1337/reportbot#15]
![image](https://user-images.githubusercontent.com/57813722/70244971-57e1b180-179b-11ea-878f-f474833f970d.png)

It just gets stuck at "Starting Accounts..."
I changed nothing, and it was working till day before yesterday. Also using the accounts that I was using while it was working. Can confirm the accounts are absolutely fine.

**Comment by verdammnis** [comment]
> ![image](https://user-images.githubusercontent.com/57813722/70244971-57e1b180-179b-11ea-878f-f474833f970d.png)
> 
> It just gets stuck at "Starting Accounts..."
> I changed nothing, and it was working till day before yesterday. Also using the accounts that I was using while it was working. Can confirm the accounts are absolutely fine.

I find out what the problem is

**Comment by Jaeger33211Sec** [comment]
The Reportbot works for me.
Report with confirmation ID: 3383524129972945401 sent!

**Comment by Jaeger33211Sec** [comment]
XD let see if you can find the fix xD

**Comment by Falghere** [comment]
@Jaeger33211Sec @HuskyDotExe 
If you are looking for a report bot still have this one, it's working
https://github.com/codsec/b1rd_ReportBot_CSGO

**Comment by verdammnis** [comment]
@HuskyDotExe  new https://github.com/despa1r1337/ReportBot-v2
