### ISSUE TITLE
Stucking on the last report

### ISSUE THREAD

**Issue by Vejas04** [despa1r1337/reportbot#4]
Hello,

i set 20 Accounts on the report list. But after the 19th one the bot started to stuck and it doesnt goes on.

Yours sincerely

**Comment by verdammnis** [comment]
> Hello,
> 
> i set 20 Accounts on the report list. But after the 19th one the bot started to stuck and it doesnt goes on.
> 
> Yours sincerely

Sup, there are several reasons: 
1. account have already been used in the reporting system. (you need to wait 12 hours) 
2. the data from your account is incorrect.

**Comment by verdammnis** [comment]
Close

**Comment by Lullimaster** [comment]
Can confirm this issue still exists. 90% of the time it gets stuck on the last report and it takes around 10-20 minutes, sometimes even more to finally execute the last report. 

Can also confirm when I tried, the accounts haven't been used in the reporting system for the last 12 hrs. Also, the data is absolutely correct - I manually  logged in and checked. Also, Steam or csgo servers weren't down/having any sort of issues as per steamstat.us
