### ISSUE TITLE
Prime or not

### ISSUE THREAD

**Issue by withs** [despa1r1337/reportbot#5]
My friend we can only report with prime account is it true ?

**Comment by verdammnis** [comment]
> My friend we can only report with prime account is it true ?

in fact, I don’t know which accounts are better to use. In fact, you still get a response from the GC, no matter which accounts you use. 

you can use
1) prime
2) Newly created accounts with the game Counter-Strike: Global Offensive

**Comment by withs** [comment]
hey, thx for anwer,
you said use Ashesh3/Steam-Account-Generator but im stuck in geting capcha.
https://github.com/steam-account-creator/Steam-Account-Generator/issues/41

**Comment by verdammnis** [comment]
> hey, thx for anwer,
> you said use Ashesh3/Steam-Account-Generator but im stuck in geting capcha.
> [steam-account-creator/Steam-Account-Generator#41](https://github.com/steam-account-creator/Steam-Account-Generator/issues/41)

good evening.
Yes, I used it before I stopped confirming mail. I wrote to the creator, but so far there is no answer from him. It remains only to wait and hope for the best😥

**Comment by withs** [comment]
>  **R.I.P**

lol  hope he will update it fast ^^
do you have any solution to generate account?

**Comment by verdammnis** [comment]
> > **R.I.P**
> 
> lol hope he will update it fast ^^
> do you have any solution to generate account?


no 😥

**Comment by verdammnis** [comment]
I am closing this issue, if you have any questions about my project, please create a new issue
