### ISSUE TITLE
MatchID option?

### ISSUE THREAD

**Issue by RadicalRedemption** [despa1r1337/reportbot#7]
Is it possible to add matchID option?

**Comment by verdammnis** [comment]
I'm too lazy to do it, do it yourself

**Comment by despa1r1337** [comment]
or using my web bot - botcsgo.tk

**Comment by RadicalRedemption** [comment]
> 
> 
> or using my web bot - botcsgo.tk

It requires a password?

**Comment by RadicalRedemption** [comment]
I'm also sure u have it already implemented, but u don't want to share it.

**Comment by despa1r1337** [comment]
how did you know :С add me in discord  : steadysuffer#3260 and I'll tell you the password

**Comment by RadicalRedemption** [comment]
> 
> 
> how did you know :С add me in discord : steadysuffer#3260 and I'll tell you the password

I've added you.
