### ISSUE TITLE
Setup a reportbot website

### ISSUE THREAD

**Issue by addee99** [despa1r1337/reportbot#8]
Hello! I've been searching for someone who can help me setup a reportbot website. No payment on the site, it should be totally free. Similar to this one https://extremereportbot.com
Of course I'll pay for the time you spend. If you can't help me, do you know someone who can? Much thanks, Adam.

**Comment by verdammnis** [comment]
> Hello! I've been searching for someone who can help me setup a reportbot website. No payment on the site, it should be totally free. Similar to this one https://extremereportbot.com
> Of course I'll pay for the time you spend. If you can't help me, do you know someone who can? Much thanks, Adam.

I can’t help you with anything.

**Comment by ghost** [comment]
Write me on discord i can help you out.
Jaeger33211#5260
