### ISSUE TITLE
Auto closing

### ISSUE THREAD

**Issue by InternalxHD** [despa1r1337/reportbot#9]
The cmd doesn't close by itself after an hour.. does that mean it doesn't work ?

**Comment by verdammnis** [comment]
please specify which bat file are you running?

**Comment by verdammnis** [comment]
if you launched the bat file "Start Report Bot.bat" and after successful work cmd did not close, then this is normal, close it yourself.

**Comment by InternalxHD** [comment]
Oh ok, got it, thanks

**Comment by verdammnis** [comment]
solved?

**Comment by InternalxHD** [comment]
yes its solved (reportbot.bat), because in your description it says dont close it manually but it didn't close by itself so thats why i asked

**Comment by verdammnis** [comment]
I pointed out that you can not close the console during the process (report) 

If you want the console to close after the successful completion of the process, right-click on the file " Start Report Bot.bat", then click "edit", in the editor delete the line "pause", save the file. After that, after a successful report process, the console will close. If you do not want it to close on its own, then leave it as it is.


Thank you for contacting Us, if you have any further problems, please open a new Issue❤️
